### ISSUE TITLE
Signing in to GitHub via Visual Studio's interface (text fields and whatnot) is not visible. Only "Sign in with your browser" is available.

### ISSUE THREAD

**Issue by snekboss** [github/VisualStudio#2526] opened 2020-06-29 14:59 UTC
## Versions
 - GitHub Extension for Visual Studio version: 2.11.104.25275
 - Visual Studio version: Community 2019 Version 16.6.2

## What happened
Connect To GitHub does not let me login in-place. It forces me to sign in via browser.

This happened to me a few days ago with the same versions. I reinstalled GitHub related things about 5 times. I don't know what happened but it worked (the username and password fields became available). After 1-2 days, they were gone again, and hence I'm creating this issue.

### Steps to Reproduce
Anything that requires me to sign in to GitHub via Visual Studio. For example:
1) Team Explorer
2) Manage Connections
3) Click the "Connect..." button for GitHub.

### Expected behavior
I expect it to show me 2 options:
1) Sign in via Visual Studios text boxes and whatnot. (This is the problem. Not seeing this.)
2) Sign in with your browser option (this is the only thing available).

Example of what I expect can be found in this YouTube video at time stamp 06:21 :
https://youtu.be/csgO95sbSfA?t=381

### Screenshots
The username and password fields are not available to me.

![github](https://user-images.githubusercontent.com/62026503/86020065-b87e5780-ba27-11ea-9844-f5959d601890.png)
![github 2](https://user-images.githubusercontent.com/62026503/86021322-427af000-ba29-11ea-8c86-d2dfefa592c7.png)

**Comment by snekboss** [comment] 2020-06-29 20:02
Ok. I uninstalled Git for Windows and GitHub extension for Visual Studio. Then, I first installed Git for Windows; and then GitHub extension for Visual Studio. The login screen is back. However, I have a feeling that it'll be gone again tomorrow. It happened before.

![github 3](https://user-images.githubusercontent.com/62026503/86050390-14f76c00-ba54-11ea-8ad3-d7f1d9f53da9.png)

**Comment by snekboss** [comment] 2020-06-30 14:34
And it's gone again. I won't post any more comments because I don't want to spam this thread. But the issue is present.

![github 4](https://user-images.githubusercontent.com/62026503/86138878-51c47100-baef-11ea-8d27-f6fbb2f58c56.png)

**Comment by jcansdale** [comment] 2020-07-06 23:18
@snekboss,

> Sign in via Visual Studios text boxes and whatnot. (This is the problem. Not seeing this.)

This is actually by design, but I admit it doesn't look very pretty!

The reason is that authenticating using passwords is going away, see:
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/

Apps will soon need to use the web application flow to obtain OAuth tokens. Another possibility would be to require users to create and enter a PAT with the correct scopes.

I'm wondering if there might be a reason you can't use the `Sign in with your browser` option? If there is, please let me know!

I'm going to close this issue as by design.

**Closed by jcansdale** 2020-07-06 23:18 UTC
