### ISSUE TITLE
User icon missing in Create Gist window

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#403] opened 2016-07-06 09:04 UTC
The user icon is sometimes missing in the Create Gist window:

![image](https://cloud.githubusercontent.com/assets/1775141/16612830/5a226296-4369-11e6-8601-383cb26f5923.png)

**Comment by paladique** [comment] 2016-07-06 13:36
Do you remember what you happened to be doing before coming to this window? I'm not getting the same behavior. 

![2016-07-06 2](https://cloud.githubusercontent.com/assets/1414307/16619676/21ee3028-435d-11e6-8933-55aae3e70e06.png)

**Comment by shana** [comment] 2016-07-06 13:38
It's likely the same issue as #408

**Comment by grokys** [comment] 2016-07-06 13:58
Yeah, it seems to work most of the time, so likely the same as #408 as @shana said...

**Comment by StanleyGoldman** [comment] 2016-09-25 23:01
I sent in a pull request for #408 and I was hoping it would fix this issue as well.
I was unable to understand the cause, but the avatar will appear correctly the first time, but subsequent views don't.

**Comment by StanleyGoldman** [comment] 2017-02-01 14:54
Resolved by #584

**Closed by StanleyGoldman** 2017-02-01 14:54 UTC
Labels: bug
