### ISSUE TITLE
VS crash with last update.

### ISSUE THREAD

**Issue by NotThatBen** [github/VisualStudio#1459] opened 2018-02-03 16:47 UTC
Hello! 

- GitHub Extension for Visual Studio  version: 2.4.0.1202
- Visual Studio version: Community 2017 v.15.5.5

After last update GitHub Extension crashes VS on 'Compare with Unmodified..' command in TeamExplorer, CodeEditor..

All info attached.
[GitHub_Extention_Crash_files.zip](https://github.com/github/VisualStudio/files/1691943/GitHub_Extention_Crash_files.zip)

**Comment by grokys** [comment] 2018-02-03 17:07
Hi @NotThatBen , thanks for getting in touch. This seems to be a duplicate of #1454. We're not sure exactly why it's happening, but we hope to have a fix out on Monday. In the meantime there are a few ways you can remedy the problem:

- Install the hotfix vsix from https://ci.appveyor.com/project/github-windows/visualstudio/build/2.4.1.1219/artifacts
- Clear your MEF Cache as described [here](https://github.com/github/VisualStudio/issues/1455#issuecomment-362638935)
- Uninstall and reinstall the extension

Sorry for the inconvenience. I'm going to close this issue, please reply to #1454 if you have any more problems.

**Closed by grokys** 2018-02-03 17:07 UTC
Labels: bug, duplicate
