### ISSUE TITLE
Directory not opened when double clicking checked out repo

### ISSUE THREAD

**Issue by mponce1** [github/VisualStudio#283] opened 2016-05-03 21:47 UTC
Steps to reproduce: 
1. Go to manage connections
2. Double click a repo in local repositories (one checkout process) 
3. Go back to manage connections
4. Under github, double click repository name

Expected result: Double clicking repo opens file explorer at directory location. 
Actual result: Nothing happens for the checked out repo.

**Comment by grokys** [comment] 2016-05-30 13:20
This appears to be expected behavior: the original double click makes the repository the selected repository and the second double click invokes this line:

https://github.com/github/VisualStudio/blob/master/src/GitHub.TeamFoundation.14/Connect/GitHubConnectSection.cs#L323

Which doesn't show the dialog if the old and new repositories are the same.

@shana I guess the question is whether this should be expected behavior?

**Comment by eloekset** [comment] 2016-08-02 12:51
From the comment in **GitHubConnectSection.cs** in @grokys link, it seems impossible to switch context to a GitHub repository without a Visual Studio solution file. For instance I try to select the **DefinitelyTyped/DefinitelyTyped** GitHub repository in Team Explorer, but what happens when I double click the repo is that the Open Solution dialog appears. Since there's no solution file to open, I just have to cancel out of that dialog, but the selected project in Team Explorer stays on the previous project that I was working on.
![githubforvsissue283](https://cloud.githubusercontent.com/assets/791721/17328841/1d1f9474-58c0-11e6-9b7b-79af44227b7f.png)

To fix this issue, Visual Studio will probably have to get an update before the GitHub Extension can do what we need, if what's said in that comment is true.

**Comment by shana** [comment] 2016-08-02 12:56
Yes, unfortunately VS doesn't expose any APIs to allow switching source control contexts without a solution being opened. The local git repositories list does it because it has direct access to the private service that handles the context so the only way to do it is to use that list.

**Comment by eloekset** [comment] 2016-08-02 13:07
Ah, thanks @shana! That's a workaround. I was able to select the repo and pull latest changes. :)
![githubforvsissue283_workaround](https://cloud.githubusercontent.com/assets/791721/17329388/c01eed94-58c2-11e6-8d8c-c8c40ce2e6a6.png)

**Comment by shana** [comment] 2016-08-02 13:46
Glad you got it to work! I'll look again and see if there's any API changes that we can use to make our list work, it's really annoying as it is right now, I totally agree.

**Comment by jcansdale** [comment] 2017-02-09 11:02
There is now a workaround for switching source control contexts. I noticed this issue as well and the behavior is inconsistent. I'll fix it as part of #834.

**Comment by jcansdale** [comment] 2017-02-09 11:42
@mponce1 @eloekset, thanks for your bug report and screenies. 😄 

These issues should be fixed in PR #834.

Double-clicking on a GitHub repo should always change the source control context and navigate to the Team Explorer - Home page. From there you can open your solution (it's slightly different in the latest VS2017 RC).

For convenience, I'm attaching a pre-built version of the VSIX:
[GitHub.VisualStudio.zip](https://github.com/github/VisualStudio/files/763507/GitHub.VisualStudio.zip)

If you could confirm the fix, that would be much appreciated!

**Comment by eloekset** [comment] 2017-02-09 11:58
Thanks for the fix and the "pre-release" @jcansdale. I've tested it and can confirm that it works. I opened the DefinitelyTyped repo using the GitHub part of Team Explorer, and I got no temporary .sln file hanging around on the disk.

**Comment by jcansdale** [comment] 2017-02-09 12:51
@eloekset Thanks for confirming the fix and the extra detail. I was forgetting you'd get to seem the gory details. 😉

**Comment by grokys** [comment] 2017-02-15 14:00
Fixed by #834

**Closed by grokys** 2017-02-15 14:00 UTC
Labels: bug
