### ISSUE TITLE
Switching to a branch from a fork that contains a new file caused crash

### ISSUE THREAD

**Issue by saraford** [github/VisualStudio#579] opened 2016-10-05 22:55 UTC
- GitHub Extension version: using grokys/maintainer-workflow as of 2pm PST 4 Oct 2016
- Visual Studio version: Visual Studio 2015 Community

**What happened** (with steps, logs and screenshots, if possible)

Note: I was not able to reproduce this a second time, even after deleting local repo and re-cloning.
1. as user1 created a PR from user1's fork of user2's repo with a new file in the commit
2. as user2 in the GitHub extension checkout user1's PR
3. switch branch //note: I can't remember if I switched back to another branch and then back to user1 after I did checkout pull request

Results: crash. See stacktrace

```
System.Net.Http.HttpRequestException was unhandled
  HResult=-2146233088
  Message=An error occurred while sending the request.
  Source=mscorlib
  StackTrace:
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Octokit.Internal.RedirectHandler.<SendAsync>d__5.MoveNext() in C:\Users\saraf\repos\VisualStudio\submodules\octokit.net\Octokit\Http\HttpClientAdapter.cs:line 180
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Octokit.Internal.HttpClientAdapter.<Send>d__2.MoveNext() in C:\Users\saraf\repos\VisualStudio\submodules\octokit.net\Octokit\Http\HttpClientAdapter.cs:line 46
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Octokit.Connection.<RunRequest>d__52.MoveNext() in C:\Users\saraf\repos\VisualStudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 537
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Octokit.Connection.<Run>d__51`1.MoveNext() in C:\Users\saraf\repos\VisualStudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 528
    --- End of stack trace from previous location where exception was thrown ---
       at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
       at System.Reactive.ExceptionHelpers.Throw(Exception exception)
       at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
       at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
       at System.Reactive.ScheduledObserver`1.Run(Object state, Action`1 recurse)
       at System.Reactive.Concurrency.Scheduler.<>c__DisplayClass65_0`1.<InvokeRec1>b__0(TState state1)
       at System.Reactive.Concurrency.Scheduler.InvokeRec1[TState](IScheduler scheduler, Pair`2 pair)
       at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  InnerException: 
       HResult=-2146233079
       Message=The remote name could not be resolved: 'api.github.com'
       Source=System
       StackTrace:
            at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
            at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
       InnerException: 
```

**Comment by grokys** [comment] 2016-10-06 13:52
> The remote name could not be resolved: 'api.github.com'

Looks like this was a network error which is why you couldn't reproduce it. Did this cause VS to crash or just cause the debugger to break?

**Comment by saraford** [comment] 2016-10-06 15:35
@grokys I'm 95% certain this was a crash. I can't think of why else it would break into the debugger. I didn't have any breakpoints set, etc. Anything I could do next time to get a better stacktrace? Or is there a line I could set a breakpoint if I think I'm getting close to a repro? 

Perhaps I could try going offline during this scenario and see how it handles it when it can't reach api.github.com?

**Comment by grokys** [comment] 2016-10-11 12:02
Even if you don't have any breakpoints set, if you're running in the debugger and you have "Break on exceptions" set for `HttpRequestException` then the debugger will break. If everything is working correctly, pressing F5 a few times should allow the exception handlers to run and display an error message like so:

![image](https://cloud.githubusercontent.com/assets/1775141/19269473/11e7a11e-8fbb-11e6-828f-097c8e7fcccf.png)

The screenshot above was what happened when I disconnected from the network while doing the branch switch. However, as you can see the error was slightly different to the one you encountered, so it may be that the one you encountered was not handled. I'm not sure how to reproduce the exact same failure to check it though.

**Comment by meaghanlewis** [comment] 2017-11-21 22:06
Closing this out for now since we aren't able to repro. Please feel free to re-open if this is an issue still.

**Closed by meaghanlewis** 2017-11-21 22:06 UTC
Labels: bug, needs repro
