### ISSUE TITLE
Validation Failed when adding Inline-Comment

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1232] opened 2017-09-18 17:27 UTC
- GitHub Extension for Visual Studio version: 2.3.4.40 (dev)
- Visual Studio version: 2015

__What happened__ (with steps, logs and screenshots, if possible)

1. Open https://github.com/grokys/PullRequestSandbox/ in VS
2. Open details of PR 23 in GitHub pane
3. View Changes on `Program.cs`
4. Try to add comment on line 16

![image](https://user-images.githubusercontent.com/11719160/30555202-d7f01986-9c9e-11e7-9ed6-5bb1a659a025.png)

After clicking `Comment` get message `Validation Failed. Do you have a pending review comments?`

I regression was introduced with #1230.

//cc @grokys

**Comment by meaghanlewis** [comment] 2017-09-19 17:23
@jcansdale I'm unable to reproduce this issue following the steps above and commenting on many other PR's. Im also using version 2.3.4.40 and tried with both VS2015 and VS2017

**Comment by jcansdale** [comment] 2017-09-21 13:54
Yes, I'm still seeing this. I'm using a version built from `master`, which should be the same as `2.3.4.40`.

**Comment by meaghanlewis** [comment] 2017-10-18 19:43
I believe this issue is fixed by: https://github.com/github/VisualStudio/pull/1269

**Closed** 2017-10-18 19:43 UTC
Labels: bug, inline-comments
