### ISSUE TITLE
Latest version fails to install in VS2017 

### ISSUE THREAD

**Issue by KeithVinson** [github/VisualStudio#2114] opened 2018-12-07 22:26 UTC
## Versions
 - GitHub Extension for Visual Studio version: ...
 - Visual Studio version: ...

**Comment by KeithVinson** [comment] 2018-12-07 22:31
GitHub Version 2.6.0.6187. Initially the extensions were installed, then today it popped up as having an update available. When I try to update the installer fails with:
Package 'GitHub.VisualStudio,version=2.6.0.6187' failed to install. System.IO.IOException: The file 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\GitHub\GitHub\Akavache.dll' already exists.
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.<InstallCoreInternal>g__install|27_1(PackagePart part, Boolean saveExtensionManifest, <>c__DisplayClass27_0& , <>c__DisplayClass27_1& , <>c__DisplayClass27_2& , <>c__DisplayClass27_3& , <>c__DisplayClass27_4& )
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.InstallCoreInternal(String localPath, String installDir, InstallablePackage pkg)
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.<>c__DisplayClass7_0.<InstallCore>b__0()
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.DoAction(Func`1 action)
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.InstallCore(String localPath, String installDir, InstallablePackage pkg)
   at Microsoft.VisualStudio.Setup.Installer.InstallerBase.InstallHelper(InstallData installData)

**Comment by KeithVinson** [comment] 2018-12-07 22:36
[VSIXInstaller_c62b7c73-a349-431b-acdb-a5ec809c9d10.log](https://github.com/github/VisualStudio/files/2658960/VSIXInstaller_c62b7c73-a349-431b-acdb-a5ec809c9d10.log)

**Comment by shana** [comment] 2018-12-07 22:54
Thank you for the logs. This looks a problem with the VS installer itself. It's going to take a while to figure out why this is happening with Microsoft, so maybe try to uninstall the version that you have currently, and then install the new version, and see if that works?

@AArnott Any ideas on what could be going on here?

**Comment by KeithVinson** [comment] 2018-12-07 22:59
Sure, well that's the first thing I though of. Git Extensions for VS2017 doesn't appear in the windows programs uninstall section, and inside VS2017 it doesn't show as being installed, So I'm not sure how I could pull it off the system to try and do a clean install. Any ideas as to how to "remove" it from the system would be appreciated.

**Comment by AArnott** [comment] 2018-12-08 00:55
I'll loop in the folks who own this area now.

**Comment by mjcavallari** [comment] 2018-12-08 01:05
The error you are seeing has generally occurred in the past when an extension fails to uninstall as part of the update.  That causes the install of the newer extension to fail since extension installs are not allowed into over-write previously existing files.  One option here is to manually delete that file and try again.  If you end up seeing the same error with yet more files, another approach is to manually install the extension from the command line using VSIXInstaller and passing the -force switch.

**Comment by KeithVinson** [comment] 2018-12-08 01:06
OK Thanks I give it a shot

**Comment by KeithVinson** [comment] 2018-12-08 01:20
Well based on your recommendation I decided to rename the folder chain  ...GitHub\GitHub... to ...GitHub\xGitHub and then allowed VS to reinstall the GitHub Extension for Visual Studio. Bingo it worked. --closing the ticket -- 

Thanks All!

**Comment by jcansdale** [comment] 2018-12-08 10:15
@mjcavallari,

This looks similar to an issue I had the when I first tried to install an update from Visual Studio 2019 Preview 1:

Updating to latest version then fails.

![image](https://user-images.githubusercontent.com/11719160/47420950-7c392500-d777-11e8-918f-6daf2defe3a2.png)

[VSIXInstaller_355cc1bc-f779-41f7-89b0-61f856d42dc2.log](https://github.com/github/VisualStudio/files/2509960/VSIXInstaller_355cc1bc-f779-41f7-89b0-61f856d42dc2.log)

Installer got itself into an unhappy state. The extension is no longer showing up on the extension manager. Still can't install after a reboot:

[VSIXInstaller_24fcb12e-41b1-46f2-b9e2-304f8e5679b9.log](https://github.com/github/editor-tools/files/2516751/VSIXInstaller_24fcb12e-41b1-46f2-b9e2-304f8e5679b9.log)

Removed the folder from `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\GitHub`. Install now completes:

![image](https://user-images.githubusercontent.com/11719160/47423047-03889780-d77c-11e8-903f-d2344362eefd.png)

**Comment by Huy-Nguyen-MSFT** [comment] 2018-12-11 04:06
@keithvinson, @jcansdale - I could not reproduce this error for investigation. In order to investigate this issue further, would you please download / run collect.exe from https://aka.ms/vscollect and share the generated %temp%\vslogs.zip? Hopefully the log will give us a clue of what happened.

**Comment by KeithVinson** [comment] 2018-12-11 14:09
Huy,
vslogs.zip is over 28MB, so I can't drop it here. Let me know how you want the file transferred.

Keith

**Comment by Huy-Nguyen-MSFT** [comment] 2018-12-11 18:47
Thanks, Keith! Would you please follow https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017 and report this as a new problem? You can attach the vslogs.zip file to the problem as well.

**Comment by KeithVinson** [comment] 2018-12-11 23:04
well, I was able to "fix" my issue by getting rid of the Git extension directory and then reinstalling it. So at this time my installation of VS2017 is OK. I'm not sure reporting it as an issue would made sense in that the install logs might not show as issue... Should I do it anyway?

**Comment by Huy-Nguyen-MSFT** [comment] 2018-12-11 23:41
Hi Keith, even with the success work-around, this can still be potentially an issue for others :). So please feel free to open an issue and attach the full vslogs.zip file (28MB). I'm hoping to find out from that log file what may cause the break in GitHub extension update.

**Comment by KeithVinson** [comment] 2018-12-12 14:37
@Hey Huy-Nguyen-MSFT 
Here's a link to the issue over at the VS forum...
https://developercommunity.visualstudio.com/content/problem/406474/latest-version-of-github-extensions-for-vs2017-fai.html

**Comment by Huy-Nguyen-MSFT** [comment] 2018-12-12 16:58
Thanks very much, Keith! I think we can close this issue and we'll track the feedback item on VS side.

**Closed** 2018-12-12 19:09 UTC
