### ISSUE TITLE
Opening a context menu takes 1-2 secs when project is not hosted on github

### ISSUE THREAD

**Issue by 0xd4d** [github/VisualStudio#420] opened 2016-07-06 18:27 UTC
**Version**: 2.0 Beta 1
**VS Version**: VS 2015 Update 3
1. Create a project and host it on eg. bitbucket.com
2. Open project in VS
3. Right-click in a source file

**Expected Behavior**:

Context menu opens immediately

**Actual Behavior**:

Context menu is shown after 1-2 seconds.

The reason is that the extension gets NotFound result back from the server.

If the extension is only meant to support github.com, then perhaps it should ignore any other sites.

**Comment by shana** [comment] 2016-07-06 18:58
@0x4d4 Thank you so much for the report! We support github enterprise github instances as wel, which are not hosted on github.com, so we can't rely on urls alone. The context menus shouldbe timing our early though, to not block the UI, it should only be delaying things for 250ms at most. We'll look into it!

**Comment by StanleyGoldman** [comment] 2016-09-25 16:29
I debugged this scenario, I'm not sure if the bug existed previously, but currently I can confirm the `IsGitHubDotComUri` function is working correctly. Otherwise, if there is a connection error, the context menu won't be delayed longer than 250ms.

**Comment by grokys** [comment] 2017-02-15 11:37
I too am unable to reproduce this in the latest version of the extension, so closing. @0xd4d please re-open if you're still having this problem.

**Closed by grokys** 2017-02-15 11:37 UTC
Labels: bug
