### ISSUE TITLE
Error logging in while cloning from Bitbucket on VS Enterprise 2017

### ISSUE THREAD

**Issue by rakjashn** [github/VisualStudio#1868] opened 2018-08-21 00:17 UTC
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio version: 2.5.2.2500
- Visual Studio version: Microsoft Visual Studio Enterprise 2017 
Version 15.8.1

Detailed steps:
-       I am copying the cloning url and then pasting it in the cloning url box.
-       Upon attempting to clone it gives me the credential box which I'm filling with the right credentials.
-       I'm talking about bitbucket here
-       I get the following in my ouput pane on Visual Studio:

_Error encountered while cloning the remote repository: Git failed with a fatal error.
HttpRequestException encountered.
   An error occurred while sending the request.
cannot spawn /c/program files (x86)/microsoft visual studio/2017/enterprise/common7/ide/commonextensions/microsoft/teamfoundation/team explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
could not read Password for 'https://#######@bitbucket.org': terminal prompts disabled_

**Comment by grokys** [comment] 2018-08-21 11:14
Hi @rakjashn, thanks for the report. This seems to be the same problem as quite a few users over at #949 are having (possibly caused by a network change to bitbucket?).

I'm going to close this issue: please take a look over at #949 for some possible solutions and post and more discussion there so we can keep everything in the same place. Representatives from MS are aware of the issue so hopefully a fix will be coming soon.

**Closed by grokys** 2018-08-21 11:14 UTC
