### ISSUE TITLE
When creating a new repository, the message in Team Explorer displays incorrectly

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#85] opened 2015-09-16 05:42 UTC
When creating a new repository, the message in Team Explorer displays incorrectly

**Steps to reproduce:**
1. Click Create 
2. Enter in required fields
3. Click Create

**Expected Results:** As a (newbie) user, I _think_ the message should display, "The repository was created successfully" or maybe "created and cloned successfully." 

**Actual Results:**  The repo is created and in Team Explorer, the message displays, "The repository was cloned successfully." Maybe VS does create/clone and I'm just mistaken though. :confused: 

![create message](https://cloud.githubusercontent.com/assets/10725993/9897242/e10bc646-5bfa-11e5-8464-c40c46ef01ee.gif)

**Comment by shana** [comment] 2015-09-16 13:08
Dupe of #54, a fix is already in master, to be out on the next release :smile:

**Closed by shana** 2015-09-16 13:08 UTC

**Comment by shana** [comment] 2015-09-16 14:27
@amytruong I published a new beta release, might be worth going through that one instead: https://github.com/github/VisualStudio/releases/tag/v1.0.15.0-beta

Just download the vsix file and double click it to install.

**Comment by amytruong** [comment] 2015-09-16 16:04
@shana: thanks for the heads up. I will definitely use the beta! :+1:
