### ISSUE TITLE
Cannot click on Github Enterprise on Sign in prompt

### ISSUE THREAD

**Issue by AmbroiseCouissin** [github/VisualStudio#1242] opened 2017-09-29 03:24 UTC
Hi!

I have a problem similar to https://github.com/github/VisualStudio/issues/12 but reversed.
I cannot click on GitHub Enterprise both on VS2015 and VS2017.

Any ideas?

**Comment by meaghanlewis** [comment] 2017-10-02 18:34
Hi @AmbroiseCouissin, thanks for writing in. Unfortunately, I'm unable to reproduce this myself, but another user recently reported the same issue as you.

Did this problem just start happening out of the blue, or did you recently update your extension?
Also, what version of the extension are you using?

**Comment by AmbroiseCouissin** [comment] 2017-10-03 01:20
Hi @meaghanlewis, 

It was the first time I use the extension. Right after downloading VS 2015 and VS 2017 on a new computer.
The version is: 2.3.3.38

Cheers!

**Comment by meaghanlewis** [comment] 2017-10-03 22:43
I'm still currently unable to reproduce this issue myself, but am trying to! Can you tell me what version of Visual Studio you are using?

Also, just to confirm, when you go to `Team Explorer - Connect`, does your tab look like this?

<img width="306" alt="screen shot 2017-10-03 at 3 42 59 pm" src="https://user-images.githubusercontent.com/10103121/31152558-9480c3f8-a851-11e7-95d2-4ac2d98cd5bf.png">

**Comment by Cliff-Miller** [comment] 2017-10-04 01:39
Thank you Meaghan!

See below picts regards my NB status.

Thanks once again!
Miller

[image: Imagem inline 1]


[image: Imagem inline 2]

[image: Imagem inline 3]




2017-10-03 19:43 GMT-03:00 Meaghan Lewis <notifications@github.com>:

**Comment by AmbroiseCouissin** [comment] 2017-10-04 01:50
Hi @meaghanlewis ,

Yes, my tab looks like your picture.

The version of visual studio I am using are: 
- Microsoft Visual Studio Enterprise 2017 Version 15.3.5
- Microsoft Visual Studio Enterprise 2015 Version 14.0.25431.01 Update 3

Cheers

**Comment by jcansdale** [comment] 2017-10-04 11:19
@AmbroiseCouissin,

Does your login prompt look like this, except with `GitHub` underlined?

![image](https://user-images.githubusercontent.com/11719160/31172993-b1f6cc50-a8fd-11e7-8cc3-4d1b5a1f4a20.png)

When I'm logged into GitHub, the prompt doesn't let me click on the GitHub option. I wonder if it's the same for you, except it thinks you're already logged into Enterprise. 😕

**Comment by jcansdale** [comment] 2017-10-04 14:41
@AmbroiseCouissin,

We think it might be related to this issue https://github.com/github/VisualStudio/issues/1094.

Could you try the following:

- Open Credential Manager from the Windows Start Menu
- Click on `Windows Credentials`
- Select the credentials related to your Enterprise server
- Click on `Remove`

Now try to sign in using GitHub for Visual Studio.

**Comment by jcansdale** [comment] 2017-10-05 09:27
@AmbroiseCouissin Just FYI, another user with this same issue had success with the above steps.  🤞 it will work for you as well.

**Comment by AmbroiseCouissin** [comment] 2017-10-06 02:02
@jcansdale It worked!

Thanks!

**Comment by grokys** [comment] 2017-12-11 15:35
This should have been fixed in #1277 and will be shipped in the next minor version.

**Closed by grokys** 2017-12-11 15:35 UTC
Labels: bug
