### ISSUE TITLE
Pull Request attempt renders a blank error message

### ISSUE THREAD

**Issue by tierninho** [github/VisualStudio#1146] opened 2017-08-16 16:55 UTC
While trying to create a PR from branch_X, I received a blank error message. 

Not sure what it was supposed to say but wanted to bring it up. Perhaps it was trying to mimic the inline comments error msg?

The private test repo is here:
https://github.com/tierninho-tester/TestRepo/

<img width="821" alt="screen shot 2017-08-16 at 12 44 16 pm" src="https://user-images.githubusercontent.com/14828183/29375104-d9d789f0-8281-11e7-9314-2cd68f5f27ae.png">

Re: 2.3.0.16/GitHub.VisualStudio.vsix

**Comment by grokys** [comment] 2017-08-16 16:58
I believe this is a duplicate of https://github.com/github/VisualStudio/issues/1131, which is fixed in #1133, so closing. Please reopen if you think it's not.

**Closed by grokys** 2017-08-16 16:58 UTC
Labels: bug, duplicate
