### ISSUE TITLE
2.3.2.32 fails to install to VS 2017 with "A value for 'Component' needs to be specified in the catalog."

### ISSUE THREAD

**Issue by BladeMF** [github/VisualStudio#1213] opened 2017-09-01 07:16 UTC
Today an update showed up and it fails to update. Tried two times. My VS is version 15.3.3.

I have attached the install log.

[VSIXInstaller_c5acfac7-b477-48c5-9952-7b0d7840945c.txt](https://github.com/github/VisualStudio/files/1269436/VSIXInstaller_c5acfac7-b477-48c5-9952-7b0d7840945c.txt)

**Comment by grokys** [comment] 2017-09-01 07:28
Hi @BladeMF,

Unfortunately there is a known problem with the VSIX installer in Visual Studio 15.3, Microsoft are working on a fix, but in the meantime could you try the instructions they provided here? https://github.com/github/VisualStudio/issues/1206#issuecomment-326053090

**Comment by BladeMF** [comment] 2017-09-01 07:31
Hi @grokys,

I guess I can wait for a fix from MS, it's not that crucial yet. I just thought I'd let you know. I'm guessing you're positive that this is the same bug or not some incompatibility?

**Comment by grokys** [comment] 2017-09-01 07:35
I'm not positive this is the same bug (@Michael-Eng does this look like the same problem to you?), however, I suspect that the fix/workaround will be the same.

**Comment by shana** [comment] 2017-09-01 10:22
This doesn't look like the same bug, it looks like a packaging issue. @BladeMF Which version of the extension do you currently have, and how did you install it originally? From the Extensions and Updates menu, or from the Visual Studio installer when you installed VS itself?

**Comment by shana** [comment] 2017-09-01 11:14
I've been trying to repro this but no luck so far. 😞 

@BladeMF Uninstalling the extension manually might fix this problem. Could you try the following steps:

1. Shutdown VS 2017
1. Open a `Developer Command Prompt for VS 2017` in administrator mode (right-click on the Start menu shortcut and `Run as administrator`)
1. run `vsixinstaller /uninstall:c3d3dc68-c977-411f-b3e8-03b0dccf7dfc` to uninstall the currently installed extension

Hopefully that completes successfully and then you can install the latest version. 🤞

**Comment by BladeMF** [comment] 2017-09-01 13:27
Maybe to repo this you need to install this on 15.3 and then upgrade to 15.3.3 and then upgrade the extension.

I wonder if I should wait for the fix for the other bug so we can all see if they are related. If you didn't miss anything in the package, maybe it is a bug.

BTW, I haven't tried uninstalling from the UI.

**Comment by vishnu4** [comment] 2017-09-01 13:50
I have the same error
[VSIXInstaller_5107ee1d-b3e9-4de3-92ad-1566cfdf8cf0.txt](https://github.com/github/VisualStudio/files/1270412/VSIXInstaller_5107ee1d-b3e9-4de3-92ad-1566cfdf8cf0.txt)
and i tried the uninstall command  and the #1206 (comment) above, and neither helped me.

**Comment by shana** [comment] 2017-09-01 15:53
@vishnu4 When you ran the uninstall command, did it also fail in the same way? Do you have the log for that?

@tinaschrepfer @michael-eng Could this be a side effect of setting the static install location of the extension in 2.3.2.32?

**Comment by shana** [comment] 2017-09-01 15:56
@BladeMF @vishnu4 We've had problems in the past related to bugs in the VS and VSIX installer which kinda have similar symptoms. https://github.com/github/VisualStudio/issues/987#issuecomment-300839715 and https://github.com/github/VisualStudio/issues/987#issuecomment-300755269 helped in the past, could you try those steps?

**Comment by Michael-Eng** [comment] 2017-09-01 16:21
I installed the latest GitHub extension on the VS Marketplace this morning and it installed successfully.

I discussed this with Tina - We're wondering if this might be related to @BladeMF upgrading the GitHub extension. 

@BladeMF, can you please run https://aka.ms/vscollect and then put the resulting zip file somewhere we can access it (it's large)

Thanks!

**Comment by vaindil** [comment] 2017-09-01 17:32
Same issue here. Tried both of the workarounds above, neither worked. Install log is below, the error was the same both when upgrading and when running the `vsixinstall` command.

* [VSIXInstaller_90d64b94-1c22-4457-a2e9-2c3d706e2eae.txt](https://github.com/github/VisualStudio/files/1271029/VSIXInstaller_90d64b94-1c22-4457-a2e9-2c3d706e2eae.txt)
* [vslogs.zip](https://github.com/github/VisualStudio/files/1271025/vslogs.zip)

**Comment by tinaschrepfer** [comment] 2017-09-01 19:53
@BladeMF , @vaindil, do you recall what your install order was for GitHub extension?  Looking at the logs it seems like there was an attempt to upgrade from 2.3.0.24 to 2.3.1.30, which was successful, and then an attempt to upgrade from 2.3.1.30 to 2.3.2.32, which was unsuccessful.  Did you do a system restore at any point between each install?

If you can, would you mind outputting all the directories and files under Common7\IDE\Extensions and upload that somewhere?  We don't need the actual files, just the paths.

Thanks!

Tina

**Comment by BladeMF** [comment] 2017-09-02 13:47
@tinaschrepfer My current version is indeed 2.3.1.30 (haven't had any problems before).

My files are:

01.09.2017 г.  09:43    <DIR>          .
01.09.2017 г.  09:43    <DIR>          ..
18.08.2017 г.  18:37    <DIR>          0jb0linh.k5j
28.08.2017 г.  14:57    <DIR>          1dpdmeqp.yfv
28.08.2017 г.  15:02    <DIR>          1zra3rwa.nr0
28.08.2017 г.  15:02    <DIR>          5gcenb00.exe
30.08.2017 г.  01:08    <DIR>          Application
28.08.2017 г.  15:02    <DIR>          bb3pjrtu.4hg
28.08.2017 г.  15:10    <DIR>          Community
28.08.2017 г.  14:49               854 DesignersCommonPackage_Registry_Common_x86.pkgdef
28.08.2017 г.  14:49               828 DesignersCommonPackage_Registry_x86.pkgdef
28.08.2017 г.  14:49             3 912 DSLTextTemplatingRegistry_x86.pkgdef
28.08.2017 г.  14:49                86 DSLTextTemplating_FileAssoc_Sxs.pkgdef
28.08.2017 г.  15:02    <DIR>          easce2x4.boy
28.08.2017 г.  15:05    <DIR>          ecazgoto.s4s
28.08.2017 г.  14:45    <DIR>          eils2yaz.zso
28.08.2017 г.  14:57    <DIR>          Enterprise
02.09.2017 г.  06:06                 0 extensions.configurationchanged
28.08.2017 г.  15:06    <DIR>          eyxtamka.fb4
28.08.2017 г.  15:07    <DIR>          fmdmssq2.ckm
01.09.2017 г.  09:43    <DIR>          GitHub
28.08.2017 г.  15:02    <DIR>          i2gjzacw.dhn
28.08.2017 г.  15:02    <DIR>          jggihpoz.gdy
28.08.2017 г.  15:09    <DIR>          kb1u5q1t.yex
28.08.2017 г.  14:57    <DIR>          ksssvfur.xzw
28.08.2017 г.  14:49             9 174 LayerDesignerDslPackage_x86.pkgdef
06.04.2017 г.  01:44    <DIR>          Merq
28.08.2017 г.  15:10    <DIR>          Microsoft
28.08.2017 г.  14:49               229 ModelingProjectTargets_x86.pkgdef
28.08.2017 г.  14:49                87 ModelingProject_Registry_FileAssoc_SxS_x86.pkgdef
28.08.2017 г.  14:49               934 ModelingProject_Registry_Pkg_x86.pkgdef
28.08.2017 г.  15:10    <DIR>          Mono.Debugging
28.08.2017 г.  15:06    <DIR>          nxfodbrb.0f1
10.03.2017 г.  17:26    <DIR>          Professional
28.08.2017 г.  14:49                87 Progression_GraphDocument_FileAssoc_Sxs_x86.pkgdef
30.08.2017 г.  01:08               566 Progression_NativePackage_Component_x86.pkgdef
28.08.2017 г.  15:00    <DIR>          ProTools
30.08.2017 г.  01:06    <DIR>          pyrgfpsc.ea0
28.08.2017 г.  15:13    <DIR>          q2vm3w32.pmy
28.08.2017 г.  15:00    <DIR>          StaticAnalysis
28.08.2017 г.  15:02    <DIR>          TestPlatform
28.08.2017 г.  15:02    <DIR>          TestWindow.Dotnet
28.08.2017 г.  15:07    <DIR>          uant3xwi.dix
28.08.2017 г.  14:56    <DIR>          uhuqfcub.t3o
28.08.2017 г.  15:12    <DIR>          VSSDK
28.08.2017 г.  15:10    <DIR>          WorkflowDesigner
28.08.2017 г.  15:02    <DIR>          wx2hgjbe.s2d
28.08.2017 г.  15:11    <DIR>          Xamarin.Android.Sdk
28.08.2017 г.  15:11    <DIR>          Xamarin.Apple.Sdk
28.08.2017 г.  15:10    <DIR>          Xamarin.Forms
28.08.2017 г.  15:12    <DIR>          Xamarin.VisualStudio
28.08.2017 г.  15:06    <DIR>          xi44pjrj.t1t
28.08.2017 г.  15:02    <DIR>          y3kvx1nx.h3x

**Comment by jcansdale** [comment] 2017-09-04 10:07
@tinaschrepfer @Michael-Eng,

There have been a few instances where it looks like the `devenv.exe.config` file has become out of whack with the installed version of the extension. This has been a problem because we use `ProvideCodeBase` / `ProvideBindingRedirection` attributes to ensure that our assemblies can be resolved (without resorting to assembly resolve event hacks).

This was particularly noticeable when I changed to an earlier version of the extension. There was a `bindingRedirect` in the `devenv.exe.config`, that was looking for an assembly that no longer existed. The extension failed to work completely.

There have also been reports of the GitHub icon missing from the Start Page. This used to happen in the past when the assembly containing the icon couldn't be resolved by its fully qualified name. This might happen if the `devenv.exe.config` hasn't been updated and the assembly version on disk doesn't match the assembly range in the `bindingRedirect`.

Here's an example of one of the GitHub entries in `devenv.exe.config`.

```
<dependentAssembly>
    <assemblyIdentity name="GitHub.UI" publicKeyToken="bc1bd09f2901c82e" culture="neutral"/>
    <bindingRedirect oldVersion="0.0.0.0-2.3.2.33" newVersion="2.3.2.33"/>
    <codeBase version="2.3.2.33" href="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\GitHub\GitHub\GitHub.UI.dll"/>
</dependentAssembly>
```

If this wan't updated and the version on disk changed to say, `2.3.3.44`, Visual Studio wouldn't know where to find the `GitHub.UI.dll` assembly.

Is this a known issue or a likely symptom of what has been reported above?

**Comment by vaindil** [comment] 2017-09-05 19:55
@tinaschrepfer Current version is also 2.3.1.30. The result of `tree` on `Common7\IDE\Extensions` is [here](https://github.com/github/VisualStudio/files/1278712/tree.txt).

**Comment by tinaschrepfer** [comment] 2017-09-05 20:13
Regarding the original issue of not being able to upgrade to 2.3.32.  We took a look at the logs you provided (thank you!) and from our analysis it looks like the following happened:
* GitHub was upgraded from version 2.3.0.24 to 2.3.1.30, which was successful.
* An attempt was then made to upgrade GitHub to 2.3.2.32, which was unsuccessful.  

From the logs it looks like somewhere between 2.3.1.30 and the attempt to upgrade to 2.3.2.32, the setup engine somehow became unaware that 2.3.1.30 was installed.  When the attempt to upgrade to 2.3.2.32 was made the engine still thinks that 2.3.0.24 is installed, so it tries to remove that instead of 2.3.1.30, but 2.3.0.24 is already gone.  The engine did successfully install 2.3.2.32, but VSIXInstaller sees that 2.3.1.30 is still present, so it requests that 2.3.1.30 be uninstalled by calling the engine to uninstall it.  However, because the engine has no idea 2.3.1.30 was ever installed, it doesn't know what to do and the exception you see is thrown.

Unfortunately, we don't have enough logging information to explain why the engine just forgot that 2.3.1.30 was installed.  Did you run a system restore at some point or anything?  We have an item on the backlog to provide more snapshot logging information so we can trace this better.

For now, to get around this, you can manually delete 2.3.1.30 by deleting everything under Common7\IDE\Extensions\pyrgfpsc.ea0 (perhaps copy the files somewhere else first as a backup), and then run devenv /updateconfiguration.  That should load 2.3.2.32 properly.

Thanks!

Tina

**Comment by BladeMF** [comment] 2017-09-05 20:23
Hi @tinaschrepfer 

What happened was an upgrade to VS to 15.3.3 (even two upgrade). Maybe the mess happened then or earlier. Will try the delete trick and let you know.

**Comment by BladeMF** [comment] 2017-09-05 20:43
I can confirm that after deleting the files and running /updateconfiguration, VS showed that I have 2.3.2.32 installed.

**Comment by vaindil** [comment] 2017-09-05 22:16
@tinaschrepfer I also upgraded VS in between there, no system restore or anything else like that. Deleting the files and running `devenv /updateconfiguration` did indeed fix the problem. Thank you!

**Comment by vishnu4** [comment] 2017-09-05 22:39
Works for me as well. thank you.

**Comment by tinaschrepfer** [comment] 2017-09-06 20:12
Thanks for the confirmations.  We are working on a fix internally to prevent this issue from occurring in the future.  For now, please make sure that VS Installer is shut down before running VSIXInstaller.  That should prevent this issue from occurring.

Thanks!

Tina

**Comment by shana** [comment] 2017-09-08 12:14
Awesome, thank you for all the help @tinaschrepfer!

**Comment by brwilkinson** [comment] 2017-09-09 01:33
I currently have this issue, since the past 4 days on VS Enterprise 2017.

running GitHub.VisualStudio.vsix

9/8/2017 9:07:04 PM - Install Error : System.InvalidOperationException: A value for 'Component' needs to be specified in the catalog.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

I tried the following and also got the same error:

vsixinstaller /uninstall:c3d3dc68-c977-411f-b3e8-03b0dccf7dfc

9/8/2017 9:14:44 PM - Uninstalling 'GitHub Extension for Visual Studio', version 2.3.1.30.
9/8/2017 9:14:56 PM - Unable to find component in product catalog with this ID: Component.GitHub.VisualStudio,version=2.3.1.30
9/8/2017 9:14:56 PM - System.InvalidOperationException: A value for 'Component' needs to be specified in the catalog.

I removed the directory: extensions/pyrgfpsc.ea0  then ran: devenv /updateconfiguration

Then tried to install it again . . it said it was already installed. . . 

I ran the command again: devenv /updateconfiguration

Opened up VS and things seem to be fine. . . I see the extension. .  so not sure what the pyrgfpsc.ea0 was, although I confirmed it is not there and no updates are showing in VS.

Extension version 2.3.2.32 shows as installed on 9/6/2017.

**Comment by jcansdale** [comment] 2017-09-11 08:43
@brwilkinson, Thanks for the detailed information. Please let us know if you have any have any further issues updating the extension.

**Comment by BladeMF** [comment] 2017-09-13 07:41
Is this the same issue: https://developercommunity.visualstudio.com/content/problem/102178/error-installing-github-extension.html?

**Comment by grokys** [comment] 2017-12-05 18:49
@BladeMF there have been numerous updates to the installer with 15.5 which was released yesterday, do they solve your problem? A user has also managed to fix the same problem here https://github.com/github/VisualStudio/issues/1295#issuecomment-349234477 if the problem is still there.

**Comment by grokys** [comment] 2017-12-12 14:54
Closing this as there's been no reply for 7 days. If you're still having the problem, please let us know and we'll reopen!

**Closed by grokys** 2017-12-12 14:54 UTC
Labels: bug, installer
