### ISSUE TITLE
No Remote list visible/ no sign out

### ISSUE THREAD

**Issue by remberg** [github/VisualStudio#1455] opened 2018-02-02 15:53 UTC
hi,
i have just installed the latest update. Unfortunately, the logout is no longer available and no remote repos are visible anymore. (latest Extension 2.4.0.1202, Visual Studio 2017 preview)

**Comment by grokys** [comment] 2018-02-02 15:57
Hi @remberg 

Thanks for letting us know: could you share a screenshot of what you're seeing?

**Comment by drewkht** [comment] 2018-02-02 16:36
Hi, I'm also seeing this issue this morning after upgrading to the newest version. Hopefully these screenshots were what you were looking for.
![team explorer pane](https://user-images.githubusercontent.com/36053052/35744010-70223716-07fc-11e8-966c-1b31d44e039a.PNG)
<img width="302" alt="github login pane" src="https://user-images.githubusercontent.com/36053052/35744011-703ca524-07fc-11e8-8592-73b493a39b02.PNG">
<img width="265" alt="team explorer pane - expanded" src="https://user-images.githubusercontent.com/36053052/35744012-70523916-07fc-11e8-9d68-9323f329f3b7.PNG">
<img width="266" alt="team explorer pane - repo home" src="https://user-images.githubusercontent.com/36053052/35744013-7071092c-07fc-11e8-8333-693209ccb1d2.PNG">

**Comment by grokys** [comment] 2018-02-02 16:45
Thanks for the screenshots @drewkht. This looks to me like MEF getting confused, could you first get a copy of your MEF cache and then try resetting the MEF cache?

There are two ways to do this:

- The easiest way is to install this extension: https://github.com/madskristensen/ClearComponentCache
  - You can then use "Tools -> Show MEF Errors" to show the MEF log. Copy this and paste it here.
  - Then select "Tools -> Clear MEF Component Cache". Visual studio will restart, and if I'm correct all should be well
- If you don't want to install another extension:
  - Close VS
  - Go to `C:\Users\[Username]\AppData\Local\Microsoft\VisualStudio\15.0_????????` (the `????????` will be a set of letters and numbers
  - Send us the `Microsoft.VisualStudio.Default.err` file
  - Then delete that directory and restart VS. Again, hopefully the problem will be fixed

**Comment by drewkht** [comment] 2018-02-02 17:29
Hi @grokys,

I followed your instructions, starting with installing the add-on. After installing and restarting VS I didn't have an option under Tools called "Show MEF Errors", although I did have the "Clear MEF Component Cache" option.

Here's the .err file you mentioned that was located inside the ComponentModelCache folder at the filepath you provided. This is from before I used the Clear MEF Component Cache option.
[Microsoft.VisualStudio.Default.err.zip](https://github.com/github/VisualStudio/files/1690208/Microsoft.VisualStudio.Default.err.zip)

It looks like you were correct about the cause of the issue, as clearing the MEF cache and restarting VS appears to have resolved it in my case. Functionality of the GitHub extension looks to be back to normal. 

Thanks!

**Comment by grokys** [comment] 2018-02-02 17:39
Thanks for getting back to us @drewkht, glad that fixed your problem.

@AArnott @Michael-Eng it looks like we may have another installer problem - clearing the MEF cache seems to resolve it. Could the installer not be doing this properly? #1454 may be related but we have no confirmation as yet.

**Comment by remberg** [comment] 2018-02-02 18:29
I didn't have an option under Tools called "Show MEF Errors".
I used the "Clear MEF Component Cache" and it works now. Thx for help

**Comment by jcansdale** [comment] 2018-02-02 18:56
@remberg,

Could you try this new installer (open the .vsix file):
https://ci.appveyor.com/project/github-windows/visualstudio/build/2.4.1.1219/artifacts

It includes a workaround for this issue. Please let us know if this version works as expected!

**Comment by jcansdale** [comment] 2018-02-02 19:05
@remberg,

Note, you might need to open the .vsix from the .zip. I was getting a network error when tried downloading the .vsix directly. It worked fine from the .zip. 😕 

![image](https://user-images.githubusercontent.com/11719160/35750127-e089cdb2-084b-11e8-8e1d-3299b378bebe.png)

**Comment by remberg** [comment] 2018-02-02 20:03
Ok i installed the .vsix and it works. Thank you!

**Closed** 2018-02-05 08:35 UTC
Labels: bug, installer
