### ISSUE TITLE
Cannot install from .vsix W10-10240 VS2015 Enterprise Preview

### ISSUE THREAD

**Issue by chaim1221** [github/VisualStudio#28] opened 2015-08-02 02:17 UTC
The installer seems broken from the [download page][1]. I was able to install by using the `MODIFY` feature from the original vs_enterprise installer--perhaps that installer is different? 
![files](https://cloud.githubusercontent.com/assets/3819970/9024388/f14ca9e0-3881-11e5-8b27-a29825bfd0ea.png)

  [1]: https://visualstudio.github.com/

**Comment by Haacked** [comment] 2015-08-03 16:42
Hi @chaim1221. Thanks for the error report.

> The installer seems broken from the download page

Could you provide somemore details? What happened when you tried to run it?

**Comment by chaim1221** [comment] 2015-08-03 20:05
Hi @Haacked !! I tried to open the file by double-clicking it and nothing happens at all--perhaps a swallowed exception? I can check the system error logs when I'm back in my home Windows environment.

I would try it on Windows 7/VS2013 at work, but it only supports VS2015.

**Comment by Haacked** [comment] 2015-08-03 20:15
> I can check the system error logs when I'm back in my home Windows environment.

Yes, please do. Also, let us know information about the Operating System and specific version of VS 2015. For example, is it Community Edition, Pro, or Enterprise?

**Comment by chaim1221** [comment] 2015-08-03 20:17
I can tell you it's Enterprise Preview. The operating system I believe is Windows 10 Enterprise, TechNet Preview, Build 10240 but I'll confirm when home.

**Comment by shana** [comment] 2015-08-03 20:33
@chaim1221 When did you install VS? If you installed it recently, chances are you already have the latest GitHub Extension installed (because VS's installer uses the vsix on the website, it will always install the latest version). If this is the case, then trying to run the vsix again won't do anything, which seems to match what you were seeing.

**Comment by chaim1221** [comment] 2015-08-03 20:45
@shana Latest 2015 Enterprise Preview build. Yes, it has the *option* to install the GitHub 3rd Party extension but it doesn't do it automatically. The scenario here is when you don't install it during the Visual Studio install, but you want to add it afterwards.

**Comment by chaim1221** [comment] 2015-08-03 20:46
When I say latest build, I mean the latest stable build on the MS website.

**Comment by shana** [comment] 2015-08-03 20:51
@chaim1221 Try installing from the Visual Studio Gallery in VS, see if that one works.

**Comment by chaim1221** [comment] 2015-08-03 20:53
@shana I've already said that one works. Read my initial report please.

**Comment by chaim1221** [comment] 2015-08-03 20:55
Excuse the edits :)

**Comment by shana** [comment] 2015-08-03 21:00
The installer from the vs enterprise is the same one that is on the website - the vs installer downloads it directly from our website. The installer in the Visual Studio online gallery is a copy of it hosted by Microsoft, and it doesn't show up in the installed programs list. You can install the extension from the gallery by going to Tools - Extensions and Updates and searching for it in the online tab.

**Comment by chaim1221** [comment] 2015-08-03 22:49
I believe you. However, I still experienced the error. I don't know why.

**Comment by Haacked** [comment] 2015-08-03 23:15
> I believe you. However, I still experienced the error. I don't know why.

I believe you too. :smile: Hopefully the Event Viewer logs will have some clue. @shana, are there other VSIXInstaller logs to look at?

**Comment by chaim1221** [comment] 2015-08-05 07:20
.NET Runtime error, Event ID 1026

long-and-short-of-it: `UnauthorizedAccessException` (jokingly, are you root? ;) )
```
Application: VSIXInstaller.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess)
   at VSIXInstaller.Logger..ctor(System.String)
   at VSIXInstaller.Logger.InitializeLogger(System.String)
   at VSIXInstaller.Logger.get_Instance()
   at VSIXInstaller.Logger.WriteLine(System.String)
   at VSIXInstaller.App.InitializationExceptionHandler(System.Exception)
   at VSIXInstaller.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<_ctor>b__0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at VSIXInstaller.App.Main()
```

**Comment by chaim1221** [comment] 2015-08-05 07:20
I haven't tried to run the .vsix as admin but it shouldn't be necessary.

**Comment by chaim1221** [comment] 2015-08-05 07:22
Yeah, it works as admin. Quick workaround: Tell folks to run it as admin. Most people trying to run this extension will know how to do that.

**Comment by shana** [comment] 2015-08-05 12:56
The vsix installer asks for elevated permissions when it runs. Have you changed the configuration for elevation on Windows, by any chance (I don't know if it's possible to do that on Windows 10, just trying to figure out why it fails for you)

/cc @prasethu @clboles @mtbandolier - Do you have an idea why the vsix installer would be failing on Windows 10?

**Comment by Haacked** [comment] 2015-08-05 16:44
> Yeah, it works as admin.

Ok, it sounds like you have it working. We can close this issue out while we follow up with the VS team to see if there's issues with Win10 and VSIX.

**Closed by Haacked** 2015-08-05 16:44 UTC
Labels: bug

**Comment by chaim1221** [comment] 2015-08-05 16:49
Yes, I believe I changed the UAC to be *less* restrictive. Probably a Windows 10 thing, then. Thanks for looking at it.

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Wed, Aug 5, 2015 at 9:44 AM -0700, "Phil Haack" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, it works as admin.

Ok, it sounds like you have it working. We can close this issue out while we follow up with the VS team to see if there's issues with Win10 and VSIX.

�

**Comment by codymullins** [comment] 2015-09-02 02:58
I can confirm, I'm having the same issue with Windows 10 Pro. VSIX installers give me an unauthorized access exception, but I am able to use the extension manager in Visual Studio successfully.

**Comment by andre-artus** [comment] 2015-09-04 17:50
I had the same/similar issue with another extension. Installing as admin worked.

https://github.com/ligershark/side-waffle/issues/302

**Comment by davemvp** [comment] 2015-09-04 22:40
I am also following ligershark/side-waffle#302 and came across this thread. I tested on two machines. One worked without admin privileges and the other didn't. On the computer that required elevated privileges I have SQL Server 2014 and IIS installed. The computer that didn't require elevated privileges had neither of these applications / features.

**Comment by andre-artus** [comment] 2015-09-04 22:49
I had SQL 2014 installed previously, but had 2016 installed at the time the
issue arose.
I also have IIS installed.

**Comment by shana** [comment] 2015-09-07 10:19
Just fyi, for anyone stumbling onto this, this looks to be a bug with the vsix installer, which happens when the vsix requires elevated permissions but for some reason the elevated permissions prompt is never shown (perhaps because the user changed the UAC settings to be less strict). MS is investigating the issue. If this hits you, try installing the vsix with admin privileges.

**Comment by sayedihashimi** [comment] 2015-09-08 20:41
@Haacked 
>Ok, it sounds like you have it working. We can close this issue out while we follow up with the VS team to see if there's issues with Win10 and VSIX

This is impacting some community work as well (i.e. SideWaffle/WebEssentials). If we close this out how are community members supposed to get updates to this issue?

**Comment by shana** [comment] 2015-09-08 20:49
@sayedihashimi This is not a bug that we have any control of, nor will MS update this issue if/when they fix it. This is not the right place to follow up on a windows bug. The best place is probably MS's feedback/bug reporting tool.

**Comment by sayedihashimi** [comment] 2015-09-08 20:51
@shana sorry I just realized this is the github org and not VisualStudio. I'll followup with the VS team by email and will post an update to https://github.com/sayedihashimi/slow-cheetah/issues/178 if I get any.

**Comment by chaim1221** [comment] 2015-09-08 21:48
Starting to feel a little bad about this, apparently it is high in Google results or something. Again, this is a Windows 10 problem and the workaround is:

> Run the .vsix file as administrator

@shana: Feel free to delete this bug if it's impacting work on other stuff...

**Comment by shana** [comment] 2015-09-08 22:10
@chaim1221 Nah, it's :cool:, it's useful information :-)
