### ISSUE TITLE
Cloning dialog never exits after cloning from roaming profile

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#1427] opened 2018-01-23 16:58 UTC
In 2017, when cloning a very small repository from the roaming profile (Start Page), the cloning dialog just sat there spinning after the clone was finished, I had to manually close it. I suspect it hung waiting for the event that tells it the clone is done (can't remember how/if we check for that), because the NumberOfClones metrics never got updated (and that's done after we think we're done with the cloning).

**Comment by grokys** [comment] 2018-01-23 17:29
I've tried to repro this with the same version of GHfVS and the same repository but been unable to. It could be related to being a fresh install?

I managed to get a similar bug by causing the dialog to open without Team Explorer open; the spinner was shown but the clone view was never shown in it. From testing this scenario on `master`, that seems to be fixed. Maybe this is fixed too? We can hope...

**Comment by meaghanlewis** [comment] 2018-01-24 22:46
I just tried to repro this from the latest build on master, but was unable to do so as well.

**Comment by meaghanlewis** [comment] 2018-09-11 21:00
Closing this issue out for now since we haven't been able to reproduce it. Please re-open if you experience this behavior again.

**Closed by meaghanlewis** 2018-09-11 21:00 UTC
Labels: bug, needs repro
