### ISSUE TITLE
Sticky new comments

### ISSUE THREAD

**Issue by ungb** [github/VisualStudio#1046] opened 2017-07-07 20:47 UTC
Adding a comment to a line in green gutter scroll section works, however the comment is not found if I were to click on that line again. The comment count in the GH window does not increment either.

<img width="644" alt="screen shot 2017-07-07 at 10 19 06 am" src="https://user-images.githubusercontent.com/14828183/27961999-8da1ec12-62fe-11e7-8d3a-42fc82d806ac.png">

I can see the comment in PR on dotcom though. Not sure if this is the correct functionality. I would expect the comment to be sticky in VS and the comment count to increment.

<img width="1130" alt="screen shot 2017-07-07 at 10 20 18 am" src="https://user-images.githubusercontent.com/14828183/27962027-9dc17bd0-62fe-11e7-95e8-6fd0f5d56f08.png">

(contact @tierninho for questions)

**Comment by grokys** [comment] 2017-07-14 13:05
Duplicate of #1052

**Closed by grokys** 2017-07-14 13:05 UTC
Labels: bug, inline-comments
