### ISSUE TITLE
PR adding review comment request fails for HTTP enterprise server

### ISSUE THREAD

**Issue by pmunin** [github/VisualStudio#2224] opened 2019-02-12 02:11 UTC
## Versions
 - GitHub Extension for Visual Studio version: 2.7.1.6591
 - Visual Studio version: 2017 Pro

## What happened

I have github for enterprise intranet server deployed. There server only supports http connection (HTTP://github.{mycompany}.com). When works fine, until I try to add a comment for PR, it shows "An error occurred while sending the request". In Fiddler I can see, that it tries to send requests to HTTPS:443 tunnel, even though all other requests work fine and go through HTTP:80, including showing list of available PRs and shows existing comments fine.

### Steps to Reproduce
1. Add local Github for Enterprise deployed to local HTTP (not HTTPs) server
2. Open some active PR for review in Visual Studio
3. Try to add new review comment for the PR
4. See error "An error occurred while sending the request"

### Expected behavior

Successfully add request

### Screenshots

![image](https://user-images.githubusercontent.com/7120440/52606662-6a23e500-2e41-11e9-9855-c0e705ce0eca.png)

![image](https://user-images.githubusercontent.com/7120440/52606736-a5beaf00-2e41-11e9-94e0-4cc114bd86f9.png)

**Comment by jcansdale** [comment] 2019-03-25 11:33
Hi @pmunin,

Sorry about the delay getting back to you!

I've been doing some investigation as it isn't obvious why it would be doing this. We should be preserving the HTTP or HTTPS protocol of the host.

Could you try using the `File > Open > Open from GitHub...` command and let me know if the repository list appears for your Enterprise server? This uses GraphQL just like the API for posting a comment.

**Comment by pmunin** [comment] 2019-03-25 19:24
Just tried your advice, opened/cloned github repo from file/Open menu - same story, opens PR, and shows changes, but fails to add any comments to it

**Comment by jcansdale** [comment] 2019-03-26 09:38
Thanks for letting me know. This is strange because the open/clone dialog uses GitHub v4/GraphQL API. I thought initially that the GitHub v4/GraphQL API might always be using HTTPS.

I'm wondering if the issue might be the version of GitHub Enterprise you're using rather than HTTPS? Do you know which version you have installed?

**Comment by pmunin** [comment] 2019-03-26 14:56
It says `Enterprise Server 2.13`, when I open github/help

**Comment by StanleyGoldman** [comment] 2019-03-28 20:30
I have able to reproduce this issue using Enterprise 2.1.3 over http.

**Comment by jcansdale** [comment] 2019-03-29 15:48
Hi @pmunin,

We're hoping this issue is fixed in #2305.

Could you try installing the VSIX from the following location and let me know if that resolves the issue
https://ci.appveyor.com/project/github-windows/visualstudio/builds/23437511/artifacts

If you could comment on #2305, that would be great. 😄

**Comment by pmunin** [comment] 2019-03-29 22:57
Just tested, works now! 👍 replied to #2305 as well.

**Closed** 2019-03-29 23:01 UTC
Labels: bug
