### ISSUE TITLE
Extension created submodule and I can't remove it

### ISSUE THREAD

**Issue by username30** [github/VisualStudio#2414] opened 2019-09-10 11:02 UTC
Hello,
Your extension created submodule in my solution instead of pushing corresponding project code towards git. And I can't remove it in any way not from Visual Studio, nor from web.
Please fix it, since now I have to create new repository instead of broken old one.

I use Visual studio 2019 Community v16.2.4

**Comment by SynovialWheat9011** [comment] 2019-09-10 14:18
Bonjour.

**Comment by Adrian79Bi** [comment] 2019-09-10 17:05
Fuck me anal

**Comment by jcansdale** [comment] 2019-09-13 12:08
I'm confused about this. GitHub for Visual Studio doesn't contain any submodule creation functionality. Were you using the Team Explorer or GitHub tool window when this happened?

I'm closing for the moment because I'm pretty sure this isn't a GitHub for Visual Studio issue. Feel free to comment if you think I'm mistaken!

**Closed by jcansdale** 2019-09-13 12:08 UTC

**Comment by username30** [comment] 2019-09-16 11:15
@jcansdale it doesn't and that's the issue. I've created new repository with exactly GitHub extension for Visual Studio. One of this solution's project happened to contain some .git folders and info. Resulting, it was added as submodule and I was unable to bring it normal back.

What behavior i expect:
- or your extension should contain tools to work with submodules to fix such issues
- or your extension should not add projects into repository as submodules and add exactly source code of project's files

**Comment by jcansdale** [comment] 2019-09-16 11:35
Could you send a screenshot that shows where the issue is? I wonder if this is a Team Explorer issue rather than a GitHub for Visual Studio issue.  Have you been using the `Team Explorer` tool window or the `GitHub` tool window?

**Comment by username30** [comment] 2019-09-16 11:45
I used this tab. But it's the only with proper sync tools. "GitHub" tab below contains only pull request management.

![1](https://user-images.githubusercontent.com/24947452/64955243-6604ed80-d890-11e9-9596-e09d285a1b3c.PNG)

**Comment by username30** [comment] 2019-09-16 11:48
I used this tab. But it's the only with proper sync tools. "GitHub" tab below contain only some pull management tools.

![1](https://user-images.githubusercontent.com/24947452/64955397-d01d9280-d890-11e9-83b4-d65293b04da8.PNG)
