### ISSUE TITLE
Feature Request: Support SAML authentication for GHE

### ISSUE THREAD

**Issue by cryps1s** [github/VisualStudio#1003] opened 2017-05-27 23:30 UTC
Hey GitHub, thanks for putting together this awesome plugin.

Our Github Enterprise instance relies on SAML authentication, which is unfortunately not supported by this plugin. Any attempt to authenticate just returns a generic "Incorrect password" error message.

I checked over the open PRs and issues and didn't see any mention of SAML -- so here's a ticket requesting it.

Thanks!

**Comment by grokys** [comment] 2017-05-30 09:05
Hi @cryps1s 

Yes this is something we've been investigating. From what I understand, the problem is that to login via SAML a browser is required and the browser shipped with VS (even VS2017) is very old and unable to do it. So we'd either need to:

1. Embed a newer browser in the extension
2. Call out the the system browser and somehow retrieve the token from there

It's definitely something we need to investigate in more depth however, thanks for filing the issue!

**Comment by Haacked** [comment] 2017-05-30 18:30
> Call out the the system browser and somehow retrieve the token from there

One simple way to retrieve the token is to do what Atom does. It simply presents the token in a nice page with a "click to copy" button. Then the user can paste it into the extension. Not as ideal as automatically retrieving the token, but it would work.

I _thought_ that Visual Studio launches a browser when you log into VSO. So I wonder if there's a way to retrieve the token the same way they do.

**Comment by chauncat** [comment] 2017-06-01 14:38
According to this it looks like that is the way Microsoft intended this to work.

https://www.visualstudio.com/en-us/docs/setup-admin/team-services/use-personal-access-tokens-to-authenticate

**Comment by chriszo111** [comment] 2018-08-07 08:32
Is this issue still ongoing? I stumbled across the same issue, have to log in to enterprise and am not able to because SAML is not supported.

**Comment by grokys** [comment] 2018-08-07 08:59
Hi @chriszo111 - this should now be supported. You should be able to log in using [SSO on enterprise](https://github.com/github/VisualStudio/blob/master/docs/getting-started/authenticating-to-github.md) which should support SAML.

Please let us know if this works or not, and we can close this issue!

**Comment by chriszo111** [comment] 2018-08-07 09:07
I have the latest version installed
<img width="697" alt="image" src="https://user-images.githubusercontent.com/7249742/43766024-b2b76502-9a31-11e8-81ca-418e90347587.png">
and when I try to log in to our enterprise GH, it show's me incorrect password:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/7249742/43766177-137506ce-9a32-11e8-9940-5de90f2c8ed7.png">
What am I doing wrong?

**Comment by chriszo111** [comment] 2018-08-07 09:28
@grokys thanks for the hint, I thought I had the latest version because I just installed the extension, but I still had to update after installing the extension. It works like a charm with this version. Thanks for the fast help!

**Comment by grokys** [comment] 2018-08-07 11:30
Thanks for confirming @chriszo111 - looks like we can close this issue then ;)

**Closed by grokys** 2018-08-07 11:30 UTC
Labels: enhancement
