### ISSUE TITLE
There's no way to refresh the list of repositories

### ISSUE THREAD

**Issue by fubar-coder** [github/VisualStudio#24] opened 2015-07-31 11:42 UTC
It seems that there is no way to refresh the list of GitHub repositories which is annoying, because sometimes only a sign out and sign in allows me to see newly forked repositories (not even a VS restart seems to help).

**Comment by Haacked** [comment] 2015-07-31 16:30
Thanks for the report! Yeah, we need to periodically check for this. I think I have some code I can steal from GHfW for this.

**Comment by Haacked** [comment] 2015-07-31 16:37
This is a dupe of #6

**Closed by Haacked** 2015-07-31 16:37 UTC
Labels: bug, duplicate
