### ISSUE TITLE
Github extension 2.4.0.1202 is causing a crash in Visual Studio 2017 15.5.5 when comparing files

### ISSUE THREAD

**Issue by benrhere** [github/VisualStudio#1458] opened 2018-02-03 13:46 UTC
- GitHub Extension for Visual Studio  version: 2.4.0.1202
- Visual Studio version: 15.5.5

__What happened__ (with steps, logs and screenshots, if possible)
Just do a "compare with unmodified." VS will crash. I've repro'd this on two separate environments. This is happening consistently, and I've seen others report it happening as well.

**Comment by grokys** [comment] 2018-02-03 14:20
Hi @benrhere, thanks for getting in touch. This seems to be a duplicate of #1454. We're not sure exactly why it's happening, but we hope to have a fix out on Monday. In the meantime there are a few ways you can remedy the problem:

- Install the hotfix vsix from https://ci.appveyor.com/project/github-windows/visualstudio/build/2.4.1.1219/artifacts
- Clear your MEF Cache as described [here](https://github.com/github/VisualStudio/issues/1455#issuecomment-362638935)
- Uninstall and reinstall the extension

Sorry for the inconvenience. I'm going to close this issue, please reply to #1454 if you have any more problems.

**Closed by grokys** 2018-02-03 14:20 UTC

**Comment by benrhere** [comment] 2018-02-03 14:22
Hi @grokys , sorry for the dupe and thanks for the quick response.
